### ISSUE TITLE
Basic assets and stuff

### ISSUE THREAD

**Issue by fguth** [rbsdev/nucleo-digital#1]
@EvandroLG atropela o @gibatronic , fazenufavor!

**Comment by EvandroLG** [comment]
foi!

**Comment by gibatronic** [comment]
na-na-ni-na-não

**Comment by fguth** [comment]
pra fechar a porra tem tempo, né? e cadê os commits?

**Comment by gibatronic** [comment]
tá chovendo commit

**Comment by gibatronic** [comment]
[development.nucleo-digital.divshot.io](http://development.nucleo-digital.divshot.io/)
