### ISSUE TITLE
implement footer stylizations

### ISSUE THREAD

**Issue by gibatronic** [rbsdev/nucleo-digital#12]

**Comment by fguth** [comment]
fuck yeah I'm on it.

**Comment by gibatronic** [comment]
![go get'em](http://i.imgur.com/dmnPmEm.gif)

**Comment by fguth** [comment]
que bagunça esse html/css. pelamor.

**Comment by gibatronic** [comment]
vamos trabalhar fazendo streaming pelo [Periscope](https://itunes.apple.com/us/app/id972909677)!

**Comment by evandroeisinger** [comment]
hahahe, bagunça? Tell me more about that :santa:

**Comment by fguth** [comment]
DONE!
