### ISSUE TITLE
discuss template semantics

### ISSUE THREAD

**Issue by gibatronic** [rbsdev/nucleo-digital#5]
hey @evandroeisinger @EvandroLG, I've opened this thread to discuss our template semantics, to see what you guys think.

right now everything is wrapped inside a `main` tag which doesn't make much sense to me.

the `body` tag already does that job, it's a natural wrapper. maybe we should move the `header` and `footer` elements outside and make them siblings of the `main` tag.

or we could just remove the `main` tag entirely. what do you guys think?

something like this looks the best:

```
html
├ head
└ body
  ├ header
  ├ section 1
  ├ section 2
  ├ section 3
  ├ section...
  └ footer
```

**Comment by evandroeisinger** [comment]
After taking a look at the specification of w3, i realized it makes no sense to wrap the header and footer in the main because:

> The main element represents the main content section of the body of a document or application. The main content section consists of content that is directly related to or expands upon the central topic of a document or central functionality of an application. [http://www.w3.org/TR/2012/WD-html-main-element-20121217](http://www.w3.org/TR/2012/WD-html-main-element-20121217/)

Maybe we can use this structure to keep the page semantics:

```
html
├ head
└ body
  ├ header
  └ main
  ├ ├ section 1
  ├ ├ section 2
  ├ └ section 3
  └ footer
```

**Comment by fguth** [comment]
yup

**Comment by gibatronic** [comment]
yea, that's better... but that `main` tag can be removed in my opinion. it would make sense if we had an `aside` or something. in our case, sections could be direct siblings of the header and footer.

**Comment by fguth** [comment]
the main tag can help us when resizing to responsive versions. instead of heaving each element to resize, we control through main. makes sense?

**Comment by gibatronic** [comment]
nope... we could just do that with the `body`. also it would be a better practice to just change the `html` font-size and have everything change like magic, by using `em` / `rem` units.

**Comment by fguth** [comment]
good point

**Comment by evandroeisinger** [comment]
do it

**Comment by gibatronic** [comment]
done.
